AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Lambda Function'

Resources:
  ReportRevampS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: report-unsubscription-webpage-demo-staging-123
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
          