AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Lambda Function'

Resources:
  ReportUserTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "uniqueToken"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
        DeletionProtectionEnabled: false
        PointInTimeRecoverySpecification: 
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: "uniqueToken-index"
            KeySchema:
              - AttributeName: "uniqueToken"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
        BillingMode: "PAY_PER_REQUEST"
        TableName: "report-revamp-users-demo-cf"


        